#
# Sipi Dockerfile based on centos
#
#
# it replicates the build as described on:
#     https://github.com/dhlab-basel/Sipi
#
# it also checks out the code from github
#
# you have to provide kakadu zip file in this directory
#
# $ docker build -f Dockerfile_build_centos7 -t sipi-build .
#
FROM centos:7

# install dependendies
RUN yum install -y epel-release 
RUN yum install -y \
	gcc-c++ \
	git \
	cmake \
	readline-devel \
	gettext \
	vim-common \
	zlib-devel \
	doxygen \
	unzip \
	patch \
	openssl-devel \
	nginx \
	python34 \
	python34-pip \
	file-devel \
	python34-devel
RUN pip3 install --upgrade pip
RUN pip3 install pytest
RUN pip3 install requests
RUN pip3 install psutil
RUN pip3 install iiif_validator

# checkout the code from github
RUN git clone https://github.com/dhlab-basel/Sipi.git

# copy kakadu's distribution
COPY v7_9-01727L.zip Sipi/vendor 

# build
RUN cd Sipi/build && cmake .. && make

# mage dirs for running
RUN mkdir /Sipi/images && chmod a+rw /Sipi/images
RUN mkdir /Sipi/cache  && chmod a+rw /Sipi/cache

